language: node_js
node_js:
  - "8.9.4"
services:
  - docker
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  - ng build --prod
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export IMAGE_NAME=bochwafa/frontendangular
  - docker build -t $IMAGE_NAME .
  - docker tag $IMAGE_NAME $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: frontendalltogether
